#:schema node_modules/wrangler/config-schema.json
name = "cf-create-worker"
main = "src/index.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "twikoo"
database_id = "00928791-b82d-46e6-8394-16d4dce382c9"

[[r2_buckets]]
binding = "R2"
bucket_name = "twikoo"

[vars]
R2_PUBLIC_URL = "https://twikoo.r2.959577.xyz"

[dev]
port = 5000

[observability]
enabled = false
